// flow-typed signature: 18caa2fd104a78d16a3adf83c2167f2a
// flow-typed version: <<STUB>>/github-xhr_v^0.3.2/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'github-xhr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'github-xhr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'github-xhr/dist/constants' {
  declare module.exports: any;
}

declare module 'github-xhr/dist/error' {
  declare module.exports: any;
}

declare module 'github-xhr/dist/generate' {
  declare module.exports: any;
}

declare module 'github-xhr/dist/index' {
  declare module.exports: any;
}

declare module 'github-xhr/dist/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'github-xhr/dist/constants.js' {
  declare module.exports: $Exports<'github-xhr/dist/constants'>;
}
declare module 'github-xhr/dist/error.js' {
  declare module.exports: $Exports<'github-xhr/dist/error'>;
}
declare module 'github-xhr/dist/generate.js' {
  declare module.exports: $Exports<'github-xhr/dist/generate'>;
}
declare module 'github-xhr/dist/index.js' {
  declare module.exports: $Exports<'github-xhr/dist/index'>;
}
declare module 'github-xhr/dist/util.js' {
  declare module.exports: $Exports<'github-xhr/dist/util'>;
}
